### ISSUE TITLE
error in latest cli 1.4.5

### ISSUE THREAD

**Issue by dibyarupprk** [revanced/revanced-cli#40] opened 2022-06-20 17:11 UTC
`java.nio.file.NoSuchFileException: /resources.zip`

this is what i get while building on the latest cli 1.4.5
although the 1.4.2 works

**Comment by XDream8** [comment] 2022-06-20 17:15
i get this error too even on the latest v1.8.0

**Comment by Sculas** [comment] 2022-06-20 17:23
Duplicate of #39

**Closed by Sculas** 2022-06-20 17:23 UTC
