### ISSUE TITLE
java.nio.file.NoSuchFileException: /resources.zip

### ISSUE THREAD

**Issue by old4error** [revanced/revanced-cli#51] opened 2022-06-21 18:52 UTC
revanced-cli=1.6.1    revanced-patches=1.9.0
Error:
_at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.deleteFile(ZipFileSystem.java:1973)
        at jdk.zipfs/jdk.nio.zipfs.ZipPath.delete(ZipPath.java:759)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.delete(ZipFileSystemProvider.java:191)
        at java.base/java.nio.file.Files.delete(Files.java:1152)
        at app.revanced.utils.filesystem.ZipFileSystemUtils.deleteRecursively(ZipFileSystemUtils.kt:22)
        at app.revanced.utils.filesystem.ZipFileSystemUtils.writePathRecursively$lambda-2$lambda-1(ZipFileSystemUtils.kt:29)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at app.revanced.utils.filesystem.ZipFileSystemUtils.writePathRecursively$revanced_cli(ZipFileSystemUtils.kt:27)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:35)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:103)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)_

my command:
java -jar revanced-cli-1.6.1-all.jar --experimental -a base.apk -d $(adb devices | grep -o '\b[a-f0-9]\+\b') -c -o revanced.apk -b revanced-patches-1.9.0.jar -m app-release-unsigned.apk -e amoled -e premium-heading -e disable-shorts-button -e disable-fullscreen-panels -e hide-cast-button -e microg-support --mount

**Comment by Sculas** [comment] 2022-06-21 19:04
Duplicate of #39

**Closed by Sculas** 2022-06-21 19:04 UTC

**Comment by DaTigerYT** [comment] 2022-06-21 19:22
I'm having the same issue, with the new/latest version of ...-cli, here we have no `/resources.zip` file, whereas #39 has the `/resources.zip` file but can't compile it. Quite different errors, I'd say.

**Comment by jr1221** [comment] 2022-06-21 20:05
@DaTigerYT  Both errors say resources.zip cannot be found.  See the last line of the error in #39
