### ISSUE TITLE
error passing arguments to a method which result in an empty collection and a failure compiling

### ISSUE THREAD

**Issue by miguel-gil-barroso** [revanced/revanced-cli#45] opened 2022-06-21 14:39 UTC
using this command to compile an apk for the non-root version without using adb:
`java -jar .\revanced-cli-1.5.0-all.jar -a youtube.apk -c -o revanced.apk -b .\revanced-patches-1.8.2.jar -m integrations.apk -i microg-support -i amoled -i minimized-playback -i general-ads -i video-ads -i disable-create-button -i premium-heading -i custom-branding -i hide-cast-button -i seekbar-tapping -i old-quality-layout -i disable-fullscreen-panels -t tmp --install`
gives me this error:
![image](https://user-images.githubusercontent.com/51173946/174822614-42e27b8f-b86c-4641-82bb-16bc50f1ca23.png)

going by the fact that said error seems to only happen on a few select patches, as can be seen here:
![image](https://user-images.githubusercontent.com/51173946/174823566-a1691086-dfc7-4737-88c2-faa1c9a45c3b.png)

it might be a problem with the integrations, though i haven't tried testing this theory myself yet. the patches that have failed are these:

1. minimized-playback
2. disable-create-button
3. old-quality-layout
4. microg-support
5. general-ads
6. video-ads
7. seekbar-tapping

with the others being "successfully" applied before the program crashes because resources.zip doesn't exist:
![image](https://user-images.githubusercontent.com/51173946/174825502-48c13067-ff7c-48b0-81ce-e95adb6b783c.png)

the command works for the cli version 1.4.2, but has failed on any version above it, including versions 1.4.3 and 1.4.4, which were scrapped when the cli was rolled back to version 1.4.2. after that, it has also failed on release 1.4.5 and, as the one this issue is focused on, 1.5.0

**Comment by miguel-gil-barroso** [comment] 2022-06-21 14:49
> duplicate of #39

not completely sure it's the same as #39 as there are problems before the exception is thrown for resources.zip, but i do see someone else commenting my same problem there

**Comment by Sculas** [comment] 2022-06-21 14:51
Not a duplicate of #39. This is presumably due to unfinished code from @oSumAtrIX (tracking issue: revanced/revanced-patches#42). Revert to stable versions for now (CLI 1.4.2, Patches 1.8.1).

**Comment by Canny1913** [comment] 2022-06-21 15:29
there was a resource.zip error in screenshot too
thats why i said its duplicate

**Closed** 2022-06-21 16:44 UTC
Labels: released
