### ISSUE TITLE
[error] upgrade-button-remover: app.revanced.patcher.patch.implementation.misc.PatchResultError: Collection is empty.

### ISSUE THREAD

**Issue by Shriyash-Jagtap** [revanced/revanced-cli#44] opened 2022-06-21 10:28 UTC
java -jar revanced-cli-1.5.0-all.jar -a ytm.apk -c -d 2ee55f87 -o revanced.apk -b revanced-patches-1.8.2.jar -i minimized-playback -i microg-support -i background-play -i upgrade-button-remover -i upgrade-button-remover -i codecs-unlock -i tasteBuilder-remover  --install
[skipped] amoled: Explicitly excluded.
[skipped] minimized-playback: Incompatible package.
[skipped] disable-create-button: Explicitly excluded.
[skipped] premium-heading: Explicitly excluded.
[skipped] custom-branding: Explicitly excluded.
[skipped] disable-shorts-button: Explicitly excluded.
[skipped] disable-fullscreen-panels: Explicitly excluded.
[skipped] old-quality-layout: Explicitly excluded.
[skipped] hide-cast-button: Explicitly excluded.
[skipped] microg-support: Incompatible package.
[skipped] general-ads: Explicitly excluded.
[skipped] video-ads: Explicitly excluded.
[skipped] seekbar-tapping: Explicitly excluded.
[added] upgrade-button-remover
[added] tasteBuilder-remover
[added] background-play
[skipped] exclusive-audio-playback: Explicitly excluded.
[added] codecs-unlock
[5,20] This method requires at least 1 registers, for the method parameters
[5,20] This method requires at least 1 registers, for the method parameters
[5,20] This method requires at least 1 registers, for the method parameters
[error] upgrade-button-remover:
app.revanced.patcher.patch.implementation.misc.PatchResultError: Collection is empty.
	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:264)
	at app.revanced.patcher.Patcher.applyPatches(Patcher.kt:282)
	at app.revanced.patcher.Patcher.applyPatches$default(Patcher.kt:275)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:60)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:107)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.util.NoSuchElementException: Collection is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:201)
	at app.revanced.patcher.util.smali.InlineSmaliCompiler$Companion.compileMethodInstructions(InlineSmaliCompiler.kt:57)
	at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions(InlineSmaliCompiler.kt:67)
	at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions$default(InlineSmaliCompiler.kt:67)
	at app.revanced.patches.music.layout.upgradebutton.patch.RemoveUpgradeButtonPatch.execute(RemoveUpgradeButtonPatch.kt:46)
	at app.revanced.patches.music.layout.upgradebutton.patch.RemoveUpgradeButtonPatch.execute(RemoveUpgradeButtonPatch.kt:21)
	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:262)
	... 14 more
[success] tasteBuilder-remover
[error] background-play:
app.revanced.patcher.patch.implementation.misc.PatchResultError: Collection is empty.
	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:264)
	at app.revanced.patcher.Patcher.applyPatches(Patcher.kt:282)
	at app.revanced.patcher.Patcher.applyPatches$default(Patcher.kt:275)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:60)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:107)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.util.NoSuchElementException: Collection is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:201)
	at app.revanced.patcher.util.smali.InlineSmaliCompiler$Companion.compileMethodInstructions(InlineSmaliCompiler.kt:57)
	at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions(InlineSmaliCompiler.kt:67)
	at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions$default(InlineSmaliCompiler.kt:67)
	at app.revanced.patches.music.premium.backgroundplay.patch.BackgroundPlayPatch.execute(BackgroundPlayPatch.kt:32)
	at app.revanced.patches.music.premium.backgroundplay.patch.BackgroundPlayPatch.execute(BackgroundPlayPatch.kt:16)
	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:262)
	... 14 more
[error] codecs-unlock:
app.revanced.patcher.patch.implementation.misc.PatchResultError: Collection is empty.
	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:264)
	at app.revanced.patcher.Patcher.applyPatches(Patcher.kt:282)
	at app.revanced.patcher.Patcher.applyPatches$default(Patcher.kt:275)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:60)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:107)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.util.NoSuchElementException: Collection is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:201)
	at app.revanced.patcher.util.smali.InlineSmaliCompiler$Companion.compileMethodInstructions(InlineSmaliCompiler.kt:57)
	at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions(InlineSmaliCompiler.kt:67)
	at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstruction(InlineSmaliCompiler.kt:77)
	at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstruction$default(InlineSmaliCompiler.kt:77)
	at app.revanced.patches.music.audio.codecs.patch.CodecsUnlockPatch.execute(CodecsUnlockPatch.kt:40)
	at app.revanced.patches.music.audio.codecs.patch.CodecsUnlockPatch.execute(CodecsUnlockPatch.kt:17)
	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:262)
	... 14 more
java.nio.file.NoSuchFileException: /resources.zip
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.deleteFile(ZipFileSystem.java:1973)
	at jdk.zipfs/jdk.nio.zipfs.ZipPath.delete(ZipPath.java:759)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.delete(ZipFileSystemProvider.java:191)
	at java.base/java.nio.file.Files.delete(Files.java:1152)
	at app.revanced.utils.filesystem.ZipFileSystemUtils.deleteRecursively(ZipFileSystemUtils.kt:22)
	at app.revanced.utils.filesystem.ZipFileSystemUtils.writePathRecursively$lambda-2$lambda-1(ZipFileSystemUtils.kt:29)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at app.revanced.utils.filesystem.ZipFileSystemUtils.writePathRecursively$revanced_cli(ZipFileSystemUtils.kt:27)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:35)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:107)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)

**Comment by Sculas** [comment] 2022-06-21 10:29
Duplicate of #39

**Closed** 2022-06-21 10:29 UTC
