### ISSUE TITLE
bug: YouTube crashes on launch only when patched in `revanced-cli-3.0.0`

### ISSUE THREAD

**Issue by Exconvinced** [ReVanced/revanced-cli#253] opened 2023-08-28 07:42 UTC
### Type

Other

### Bug description

Stock YouTube app, when patched with `revanced-cli-3.0.0` and installed by mounting onto a rooted device, crashes immediately on launch. Meanwhile, the same app, when patched with `revanced-manager-1.9.4` and installed via `root` method or by mounting in CLI, works flawlessly. 

### Target device specifications
Here is a common mid-range specs that I have:
```py
OS:   Android 11
Arch: arm64-v8a
Root: Magisk 26.1
```
### Tested YouTube versions
Tested some of the versions here according to [**patches.json**](https://github.com/ReVanced/revanced-patches/releases/tag/v2.189.0) of v2.189.0 release.
```py
['18.32.39', '18.29.38', '18.23.35']
```

---
#### What fails - Patch directly with `revanced-cli-3.0.0` and install by mounting
1. If not yet, install a stock YouTube app having any of the compatible versions:

    ```bat
    adb install com.google.android.youtube.apk
    ```

2. Then, patch the package file of the same app with `revenced-cli`. Choose to install over the stock app by mounting:
    ```bat
    java -jar revanced-cli-3.0.0.jar patch \
        --patch-bundle patches-2.189.0.jar \
        --merge integrations-0.117.0.apk \
        --out patched.apk \
        --exclude vanced-microg-support \
        --device-serial <device-serial> \
        --mount \
        com.google.android.youtube.apk
    ```
We expect to see the patched app open in place of the stock app. However, the app crashes on launch.

---
#### What works - Patch with Revanced Manager, then install either by root method or mounting
1. If not yet, install a stock YouTube app having any of the compatible versions:
   
    ```bat
    adb install com.google.android.youtube.apk
    ```
2. Open Revanced Manager. In Settings, toggle `Enable changing selection` to allow excluding patches.

3. In the Patcher tab, select the installed YouTube app, and uncheck `vanced-microg-support` from the patches list. Begin patching.

4. Finally, choose to install by root method. **Alternatively**, export the patched APK, then `utility install --mount` it in `revanced-cli-3.0.0`.

Here, the patched YouTube app opens just fine.

---
### Relevant log output

<details>
<summary><h4>Output from revanced-cli-3.0.0</h4></summary>

```shell
INFO: Loading patches
INFO: Setting patch options
INFO: Decoding app manifest
INFO: Export all activities excluded by default
INFO: Override certificate pinning excluded by default
INFO: Change package name excluded by default
INFO: Enable android debugging excluded by default
INFO: Remove screenshot restriction excluded by default
INFO: Spoof wifi connection excluded by default
INFO: Predictive back gesture excluded by default
INFO: Remove screen capture restriction excluded by default
INFO: Remove debugging detection excluded by default
INFO: Custom branding excluded by default
INFO: Remove player controls background excluded by default
INFO: Excluding Vanced MicroG support
INFO: Compact header excluded by default
INFO: Excluding Vanced MicroG support
INFO: Permanent shuffle excluded by default
INFO: Permanent repeat excluded by default
INFO: Remove broadcasts restriction excluded by default
INFO: Debug mode excluded by default
INFO: Sim spoof excluded by default
INFO: Deleting existing resource cache directory
SEVERE: Failed to delete existing resource cache directory
INFO: Decoding resources
INFO: Executing patches
INFO: Spoof app version succeeded
INFO: Disable auto captions succeeded
INFO: Theme succeeded
INFO: Premium heading succeeded
INFO: Wide searchbar succeeded
INFO: Disable Shorts on startup succeeded
INFO: SponsorBlock succeeded
INFO: Hide crowdfunding box succeeded
INFO: Hide watermark succeeded
INFO: Hide breaking news shelf succeeded
INFO: Hide floating microphone button succeeded
INFO: Hide email address succeeded
INFO: Hide load more button succeeded
INFO: Hide info cards succeeded
INFO: Player flyout menu succeeded
INFO: Hide seekbar succeeded
INFO: Hide layout components succeeded
INFO: Hide timestamp succeeded
INFO: Hide Shorts components succeeded
INFO: Hide filter bar succeeded
INFO: Hide album cards succeeded
INFO: Comments succeeded
INFO: Hide endscreen cards succeeded
INFO: Custom player overlay opacity succeeded
INFO: Tablet mini player succeeded
INFO: Alternative thumbnails succeeded
INFO: Return YouTube Dislike succeeded
INFO: Disable player popup panels succeeded
INFO: Hide captions button succeeded
INFO: Hide player buttons succeeded
INFO: Hide autoplay button succeeded
INFO: Hide cast button succeeded
INFO: Navigation buttons succeeded
INFO: Hide video action buttons succeeded
INFO: Enable tablet layout succeeded
INFO: Always autorepeat succeeded
INFO: Client spoof succeeded
INFO: Disable zoom haptics succeeded
INFO: Enable debugging succeeded
INFO: Open links externally succeeded
INFO: Minimized playback succeeded
INFO: Old video quality menu succeeded
INFO: HDR auto brightness succeeded
INFO: Remember video quality succeeded
INFO: Playback speed succeeded
INFO: Video ads succeeded
INFO: Hide ads succeeded
INFO: External downloads succeeded
INFO: Copy video url succeeded
INFO: Seekbar tapping succeeded
INFO: Swipe controls succeeded
INFO: Compiling modified dex files
INFO: Compiling modified resources
INFO: Aligning com.google.android.youtube_18.32.39.apk
INFO: Copying to patched.apk
INFO: Installing by mounting
INFO: Finished installing patched.apk
```

</details>

<details>
<summary><h4>Output from Revanced Manager </h4></summary>

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Alternative thumbnails succeeded
Always autorepeat succeeded
Client spoof succeeded
Comments succeeded
Copy video url succeeded
Custom player overlay opacity succeeded
Disable Shorts on startup succeeded
Disable auto captions succeeded
Disable player popup panels succeeded
Disable zoom haptics succeeded
Enable debugging succeeded
Enable tablet layout succeeded
External downloads succeeded
HDR auto brightness succeeded
Hide Shorts components succeeded
Hide ads succeeded
Hide album cards succeeded
Hide autoplay button succeeded
Hide breaking news shelf succeeded
Hide captions button succeeded
Hide cast button succeeded
Hide crowdfunding box succeeded
Hide email address succeeded
Hide endscreen cards succeeded
Hide filter bar succeeded
Hide floating microphone button succeeded
Hide info cards succeeded
Hide layout components succeeded
Hide load more button succeeded
Hide player buttons succeeded
Hide seekbar succeeded
Hide timestamp succeeded
Hide video action buttons succeeded
Hide watermark succeeded
Minimized playback succeeded
Navigation buttons succeeded
Old video quality menu succeeded
Open links externally succeeded
Playback speed succeeded
Player flyout menu succeeded
Premium heading succeeded
Remember video quality succeeded
Return YouTube Dislike succeeded
Seekbar tapping succeeded
SponsorBlock succeeded
Spoof app version succeeded
Swipe controls succeeded
Tablet mini player succeeded
Theme succeeded
Video ads succeeded
Wide searchbar succeeded
Compiling modified dex files
Compiling modified resources
Signing APK
Patched
Installing patched file using root method
Installed!
```

</details>

---
#### What also works - Using older build and older YouTube version

As a fallback solution, you could always use previous stable builds (I forgot the exact release version).

In older builds of `revanced-cli`, `integrations`, and [`patches`](https://raw.githubusercontent.com/ReVanced/revanced-patches/v2.186.0/patches.json) when the latest compatible version of YouTube was `18.23.35` (prior to the implementation of the new CLI syntax), I am able to patch YouTube `18.23.35` and mount it using the latest CLI 3.0.0 build. Here, the app works fine also:

```bat
java -jar revanced-cli-3.0.0.jar utility install \
    --mount com.google.android.youtube \
    -a com.google.android.youtube-18.23.35.apk \
    <device-serial>
```

### Conclusion
There is only a problem with the patching of YouTube on `revanced-cli-3.0.0`. At the very least, the `utility install --mount` is not broken in the latest release. The issue likely lies in [`revanced-patches.jar`](https://github.com/ReVanced/revanced-patches/releases/tag/v2.189.0).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by cyberboh** [comment] 2023-08-28 10:02
https://github.com/ReVanced/revanced-cli/issues/241

**Comment by Exconvinced** [comment] 2023-08-28 10:14
@cyberboh Nice. I forgot to mention, I also have a secondary phone with lower-end specs and I can mount YouTube `18.32.39` easily with the latest release of [`revanced-cli`](https://github.com/ReVanced/revanced-cli/releases/tag/v3.0.0), [`integrations`](https://github.com/ReVanced/revanced-integrations/releases/tag/v0.117.0), and [`patches`](https://github.com/ReVanced/revanced-patches/releases/tag/v2.189.0) when a higher-end device cannot.
```py
OS: Android 8 (EMUI 8.0.0)
Arch: arm64-v8a
Root: Magisk 26.1
```

**Comment by cyberboh** [comment] 2023-08-28 10:28
> @cyberboh Nice. I forgot to mention, I also have a secondary phone with lower-end specs and I can mount YouTube `18.32.39` easily with the latest release of [`revanced-cli`](https://github.com/ReVanced/revanced-cli/releases/tag/v3.0.0), [`integrations`](https://github.com/ReVanced/revanced-integrations/releases/tag/v0.117.0), and [`patches`](https://github.com/ReVanced/revanced-patches/releases/tag/v2.189.0) when a higher-end device cannot.
> 
> ```python
> OS: Android 8 (EMUI 8.0.0)
> Arch: arm64-v8a
> Root: Magisk 26.1
> ```

complicated issue
mybe waiting for this commit https://github.com/ReVanced/revanced-cli/commit/983ee8fcaff335ff2a9f2f6f39dd549bd35a3bd7 to be built, and hopefully the issue will be fixed

**Comment by oSumAtrIX** [comment] 2023-08-28 12:11
Really detailed and nice issue. Yeah, it seems like bumping ReVanced Patcher should fix the issue. The issue is only present on lower Android devices, which is why the bug went unnoticed to Android 12 and up users like me.

**Comment by oSumAtrIX** [comment] 2023-08-28 12:12
When the app crashes, can you capture logs using logcat?

**Comment by cyberboh** [comment] 2023-08-28 12:36
> When the app crashes, can you capture logs using logcat?

see my logcat here https://github.com/ReVanced/revanced-cli/issues/241
its same i get in this morning

**Comment by Ushie** [comment] 2023-08-28 12:49
`adb shell`
`logcat | grep AndroidRuntime` is what we do

**Comment by Exconvinced** [comment] 2023-08-28 12:52
@Ushie that looks cleaner. thanks!

**Comment by Exconvinced** [comment] 2023-08-28 12:58
Is this useful? Installed and mounted YouTube `18.32.39` from scratch.

```bat
# revanced-cli mounting the package
08-28 20:53:00.757 10979 10979 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
08-28 20:53:00.759 10979 10979 I AndroidRuntime: Using default boot image
08-28 20:53:00.759 10979 10979 I AndroidRuntime: Leaving lock profiling enabled
08-28 20:53:00.760 10979 10979 D AndroidRuntime: addProductProperty: pBrand1 is not null
08-28 20:53:00.760 10979 10979 D AndroidRuntime: addProductProperty: not brand or 7
08-28 20:53:00.764 10920 10920 D AndroidRuntime: Calling main entry com.android.commands.content.Content
08-28 20:53:00.782 10920 10920 D AndroidRuntime: Shutting down VM

# revanced-cli probably requesting root permissions
08-28 20:53:00.790 10997 10997 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
08-28 20:53:00.793 10997 10997 I AndroidRuntime: Using default boot image
08-28 20:53:00.793 10997 10997 I AndroidRuntime: Leaving lock profiling enabled
08-28 20:53:00.794 10997 10997 D AndroidRuntime: addProductProperty: pBrand1 is not null
08-28 20:53:00.794 10997 10997 D AndroidRuntime: addProductProperty: not brand or 7
08-28 20:53:00.904 10979 10979 D AndroidRuntime: Calling main entry com.topjohnwu.superuser.internal.RootServerMain
08-28 20:53:00.931 10997 10997 D AndroidRuntime: Calling main entry com.android.commands.content.Content
08-28 20:53:00.948 10997 10997 D AndroidRuntime: Shutting down VM

# YouTube app trying to open
08-28 20:53:08.648 11496 11496 F DEBUG   :       #56 pc 00000000000a52bc  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+848) (BuildId: bcf7c98ed8ff41caa563dd948e1cf5b0)
```

**Comment by oSumAtrIX** [comment] 2023-08-28 13:02
Yes, confirming the cause, the issue is solved by bumping the dependency.

**Comment by Exconvinced** [comment] 2023-08-28 13:13
@oSumAtrIX appreciated. thanks for looking into this bug.

**Closed** 2023-08-28 13:21 UTC
Labels: bug

**Comment by exconvinced** [comment] 2023-08-28 13:33
Ding ding! YouTube app no longer crashes in [`revanced-cli-3.0.1`](https://github.com/ReVanced/revanced-cli/releases/tag/v3.0.1)! Love you man @oSumAtrIX!
