### ISSUE TITLE
"Exception in thread 'main' ... InlineSmaliCompilerKt.toInstructions$default( ... )"

### ISSUE THREAD

**Issue by DaTigerYT** [revanced/revanced-cli#46] opened 2022-06-21 15:11 UTC
Here's the entire log:
![image](https://user-images.githubusercontent.com/35151380/174833385-823c8f2e-b270-4870-a758-7ed5114549a4.png)

Here's the error and stack trace:
![image](https://user-images.githubusercontent.com/35151380/174833540-aa21646b-ad85-46a7-b2d1-2ee7a9d55fa8.png)

And the written versions:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.util.List app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions$default(java.lang.String, org.jf.dexlib2.iface.Method, int, java.lang.Object)'
```
```
java -jar revanced-cli.jar -a youtube.apk -c -d R3CT40AGH8B -o youtube_revanced.apk -b revanced-patches.jar -m revanced-integrations.apk -i minimized-playback -i disable-create-button -i premium-heading -i custom-branding -i old-quality-layout -i hide-cast-button -i microg-support -i general-ads -i video-ads -i seekbar-tapping -i microg-patch --install
```

Not sure what I'm missing here.

**Comment by oSumAtrIX** [comment] 2022-06-21 15:18
Dupe of #45

**Closed by oSumAtrIX** 2022-06-21 15:18 UTC
